name: final_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  flutter_bloc: ^9.1.1
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  swagger_dart_code_generator: ^2.9.3
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/